jpowl:
  storage:
    type: redis  # 可选: memory, redis, mysql, elasticsearch
    redis:
      host: localhost
      port: 6379
    mysql:
      url: jdbc:mysql://localhost:3306/jpowl
      username: root
      password: root
    elasticsearch:
      hosts: http://localhost:9200
  
  monitoring:
    enabled: true
    log-params: false
    log-result: false
    
  actuator:
    enabled: true
spring:
  boot:
    admin:
      client:
        url: http://localhost:8080  # Admin Server的地址
        instance:
          name: ${spring.application.name}

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,jpowl
      base-path: /actuator
  endpoint:
    health:
      show-details: always
    jpowl:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}        